jobs:
  - id: weather
    cronString: "30 9,15,21 * * *"
    response:
      - type: telegram
        chatID: -1001949361275
        topicID: 2641
#  - id: lineUp
#    cronString: "*/30 * * * *"
#    response:
#      - type: telegram
#        chatID: -1001949361275
#        topicID: 139
#  - id: instagramPost
#    cronString: "* /5 * * * *"
#    response:
#      - type: telegram
#        chatID: 38840963
  - id: antiSpoilers
    cronString: "loop"
    response:
      - type: telegram
        chatID:   -1001949361275 #-1001953829719 #
        topicID: 2